import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#0d1f1a",
        "on-secondary-fixed-variant": "#444746",
        "inverse-on-surface": "#f2f0ef",
        "on-tertiary-container": "#9e7f7c",
        outline: "#727875",
        "on-tertiary-fixed-variant": "#5a413e",
        error: "#ba1a1a",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e4e2e1",
        "on-primary-fixed-variant": "#384b45",
        "surface-container": "#efedec",
        "secondary-fixed-dim": "#c5c7c5",
        "primary-container": "#10221d",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#ffdad6",
        "secondary-fixed": "#e1e3e1",
        "inverse-primary": "#b6cbc3",
        "primary-fixed-dim": "#b6cbc3",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-bright": "#fbf9f7",
        "outline-variant": "#c2c8c4",
        "on-error-container": "#93000a",
        "surface-dim": "#dbdad8",
        "surface-container-high": "#e9e8e6",
        "inverse-surface": "#303030",
        "secondary-container": "#dee0de",
        "on-tertiary-fixed": "#2a1614",
        "surface-container-low": "#f5f3f2",
        "error-container": "#ffdad6",
        "tertiary-container": "#2d1917",
        secondary: "#5c5f5e",
        primary: "#000805",
        "surface-tint": "#4f625c",
        tertiary: "#0e0202",
        "on-background": "#1b1c1b",
        "on-secondary-fixed": "#191c1b",
        "on-surface": "#1b1c1b",
        "on-primary-container": "#778b84",
        "surface-variant": "#e4e2e1",
        "tertiary-fixed-dim": "#e2beba",
        "on-secondary-container": "#606362",
        "on-surface-variant": "#424846",
        "primary-fixed": "#d2e7df",
        surface: "#fbf9f7",
        "on-error": "#ffffff",
        background: "#fbf9f7",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xl: "40px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        base: "4px",
        "container-margin": "20px",
        gutter: "12px",
        xs: "4px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        h3: ["Manrope", "sans-serif"],
        h2: ["Manrope", "sans-serif"],
        "stat-lg": ["Manrope", "sans-serif"],
        h1: ["Manrope", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.2", letterSpacing: "0.08em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        h3: ["20px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "600" }],
        h2: ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "stat-lg": ["40px", { lineHeight: "1", letterSpacing: "-0.04em", fontWeight: "800" }],
        h1: ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
export default config;
